# AWS CodeBuild specification file
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing Node.js dependencies..."
      - npm install

  build:
    commands:
      - echo "Build started on $(date)"
      - echo "Running build command..."
      - npm run build
      - echo "Verifying build output..."
      - ls -la dist/
      - echo "Copying index.html to dist..."
      - cp index.html dist/

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Final dist contents:"
      - ls -la dist/

# Define the files to be packaged and deployed to Elastic Beanstalk
artifacts:
  files:
    - server.js
    - package.json
    - package-lock.json
    - 'dist/**/*'
  discard-paths: no