branch-defaults:
  default:
    environment: null
    group_suffix: null
  main:
    environment: solar-dashboard-env
global:
  application_name: solar
  default_ec2_keyname: null
  default_platform: Node.js 22 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
